# -*- coding: utf-8 -*-
"""Build GraphRAG-Research.pptx from graph-rag-comprehended.md.

The markdown stays a readable document; this script decides how it becomes slides.
Add sections to the markdown and re-run `make deck` -- they are picked up
automatically. See LAYOUT RULES below for how structure maps to slide types.

LAYOUT RULES
  image before H1     -> full-bleed cover slide (replaces the title slide)
  # H1                -> title slide
  ## H2               -> dark section divider, then content slides for its body
  ### H3              -> its own content slide, UNLESS several consecutive short
                         H3s can be grouped into a card grid (<= 6 per slide)
  bold-led paras      -> side-by-side cards (2-4), bullets attach to a card;
                         one short line before them is a lede, a "> quote"
                         after them is the closing kicker
  numbered list (4+)  -> numbered steps slide
  image               -> full-width figure slide with caption
  table               -> designed table slide (splits past MAX_TABLE_ROWS)
  ```mermaid```       -> replaced by a pre-rendered figure via MERMAID_MAP
  long body           -> split across "(cont.)" slides rather than overflowing
"""
import os
import re
import sys
import math

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import qn

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "graph-rag-comprehended.md")
OUT = os.path.join(ROOT, "GraphRAG-Research.pptx")
BIB = os.path.join(ROOT, "refs.bib")

# --- configuration -----------------------------------------------------------
# Mermaid blocks cannot be rendered here (no mermaid CLI); map them to figures
# generated by scripts/fig_*.py instead. Key = substring found in the block.
MERMAID_MAP = {"sequenceDiagram": "graphrag-pipeline.png"}

# Captions for images whose markdown alt text is just a filename.
CAPTIONS = {
    "img.png": "The GraphRAG framework: query processor, retriever, organizer, generator "
               "(Han et al., 2025)",
    "img_2.png": "Cosine similarity: closeness of meaning as the angle between two vectors",
    "query-structurisation.png": "The five query-processing techniques, with a worked "
                                 "example of each (Han et al., 2025)",
    "knowledge-graph-entity.png": "Retrieval in three steps: entity linking, relational "
                                  "matching, then graph traversal (Han et al., 2025)",
}

DECK_SUBTITLE = "A review of the GraphRAG survey, and what we found building one"
FOOTER = "GraphRAG research"
MAX_TABLE_ROWS = 12
CARD_MAX_CHARS = 420      # a section short enough to become a card
CLOSING_FROM_LAST_PARA = True

# --- palette (matches knowledge-graph.png / graphrag-pipeline.png) -----------
INK = RGBColor(0x1B, 0x2C, 0x3B)
SLATE = RGBColor(0x3E, 0x5C, 0x76)
SLATE_DK = RGBColor(0x22, 0x37, 0x4A)
OCHRE = RGBColor(0xB0, 0x70, 0x3A)
GREEN = RGBColor(0x47, 0x79, 0x5F)
PURPLE = RGBColor(0x6D, 0x5A, 0x7B)
CARD_BG = RGBColor(0xED, 0xF1, 0xF5)
PAGE_BG = RGBColor(0xFC, 0xFD, 0xFE)
RULE = RGBColor(0xDF, 0xE4, 0xE9)
MUTED = RGBColor(0x6E, 0x75, 0x7D)
BODY = RGBColor(0x33, 0x3B, 0x43)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
ICE = RGBColor(0xC9, 0xD6, 0xE2)
TICK = RGBColor(0x3F, 0x7D, 0x58)
CROSS = RGBColor(0xB2, 0x4A, 0x3F)
ACCENTS = [SLATE, OCHRE, GREEN, PURPLE]

HFONT, BFONT = "Georgia", "Calibri"
SW, SH = 13.333, 7.5
ML, MR = 0.82, 0.82
CW = SW - ML - MR
BODY_TOP, BODY_BOT = 1.92, 6.78


# =============================================================================
# markdown parsing
# =============================================================================
BIB_FIELDS = ("title", "author", "year", "eprint", "booktitle", "journal", "url")
LIST_RE = re.compile(r"^([-*+]|\d+[.)])\s+(.*)$")
VENUE_STOPWORDS = {"on", "of", "the", "for", "and", "in", "a"}


def parse_bib():
    """Read refs.bib into a record per entry. Values must not contain braces."""
    if not os.path.exists(BIB):
        return []
    parts = re.split(r"@(\w+)\s*\{", open(BIB, encoding="utf-8").read())[1:]
    out = []
    for etype, body in zip(parts[0::2], parts[1::2]):
        rec = {"type": etype.lower(), "key": body.split(",", 1)[0].strip()}
        for f in BIB_FIELDS:
            m = re.search(rf"\b{f}\s*=\s*\{{(.*?)\}}\s*,?\s*(?:\n|$)", body, re.S | re.I)
            rec[f] = re.sub(r"\s+", " ", m.group(1)).strip() if m else ""
        out.append(rec)
    return out


BIB_RECORDS = parse_bib()


def surnames_of(author):
    """Surnames from a bibtex author field, in either 'Ada Lovelace' or
    'Lovelace, Ada' form."""
    out = []
    for name in (a.strip() for a in author.split(" and ")):
        if not name:
            continue
        out.append(name.split(",")[0].strip() if "," in name else name.split()[-1])
    return out


def load_citations():
    """Map bibtex keys to a short 'Author et al., year' label."""
    out = {}
    for rec in BIB_RECORDS:
        s = surnames_of(rec["author"])
        label = f"{s[0]} et al." if s else rec["key"]
        if s and rec["year"]:
            label += f", {rec['year']}"
        out[rec["key"]] = label
    return out


CITES = load_citations()


def _norm_title(t):
    return re.sub(r"[^a-z0-9]", "", t.lower())


def reference_meta(rec):
    """The line under a reference: authors, venue, year, arXiv id."""
    venue = rec["booktitle"] or rec["journal"]
    if len(venue) > 40:   # long venue names read better as their initials
        ini = "".join(w[0] for w in re.findall(r"[A-Za-z]+", venue)
                      if w.lower() not in VENUE_STOPWORDS)
        venue = ini.upper() if len(ini) >= 3 else venue
    s = surnames_of(rec["author"])
    author = "" if not s else (s[0] if len(s) == 1 else
                               " & ".join(s) if len(s) == 2 else f"{s[0]} et al.")
    bits = [b for b in (author, venue, rec["year"]) if b]
    if rec["eprint"]:
        bits.append("arXiv:" + rec["eprint"])
    return "  \u00b7  ".join(bits)


def bibliography_entries():
    """Unique references, alphabetical by first author. A paper held twice --
    typically a preprint plus its published version -- collapses to one entry
    keeping the longer title, the earlier year, and both venues."""
    merged = []
    for rec in sorted(BIB_RECORDS, key=lambda r: -len(r["title"])):
        norm = _norm_title(rec["title"])
        hit = next((m for m in merged
                    if _norm_title(m["title"]).startswith(norm)
                    or norm.startswith(_norm_title(m["title"]))), None)
        if hit is None:
            merged.append(dict(rec))
            continue
        for f in ("eprint", "booktitle", "journal", "url"):
            hit[f] = hit[f] or rec[f]
        if rec["year"] and rec["year"] < hit["year"]:
            hit["year"] = rec["year"]
    return sorted(merged, key=lambda r: ((surnames_of(r["author"]) or [""])[0].lower(),
                                         r["year"]))


MATH_WORDS = {
    "dots": "…", "ldots": "…", "cdots": "⋯", "times": "×", "cdot": "·", "div": "÷",
    "pm": "±", "approx": "≈", "sim": "∼", "simeq": "≃", "equiv": "≡", "propto": "∝",
    "neq": "≠", "ne": "≠", "leq": "≤", "le": "≤", "geq": "≥", "ge": "≥",
    "ll": "≪", "gg": "≫", "in": "∈", "notin": "∉", "subset": "⊂", "subseteq": "⊆",
    "supset": "⊃", "supseteq": "⊇", "cup": "∪", "cap": "∩", "emptyset": "∅",
    "setminus": "∖", "forall": "∀", "exists": "∃", "infty": "∞", "sum": "∑",
    "prod": "∏", "sqrt": "√", "partial": "∂", "nabla": "∇", "langle": "⟨",
    "rangle": "⟩", "lVert": "‖", "rVert": "‖", "mid": "|", "vert": "|",
    "star": "⋆", "circ": "∘", "top": "⊤", "bot": "⊥", "angle": "∠",
    "to": "→", "rightarrow": "→", "Rightarrow": "⇒", "leftarrow": "←",
    "Leftarrow": "⇐", "leftrightarrow": "↔", "mapsto": "↦", "hookrightarrow": "↪",
    "land": "∧", "lor": "∨", "neg": "¬", "therefore": "∴", "because": "∵",
    "alpha": "α", "beta": "β", "gamma": "γ", "delta": "δ", "epsilon": "ε",
    "varepsilon": "ε", "zeta": "ζ", "eta": "η", "theta": "θ", "iota": "ι",
    "kappa": "κ", "lambda": "λ", "mu": "μ", "nu": "ν", "xi": "ξ", "pi": "π",
    "rho": "ρ", "sigma": "σ", "tau": "τ", "upsilon": "υ", "phi": "φ", "chi": "χ",
    "psi": "ψ", "omega": "ω", "Gamma": "Γ", "Delta": "Δ", "Theta": "Θ",
    "Lambda": "Λ", "Xi": "Ξ", "Pi": "Π", "Sigma": "Σ", "Phi": "Φ", "Psi": "Ψ",
    "Omega": "Ω",
}
# Unicode has no subscript/superscript for every character; a script is only used
# when every character in it maps, otherwise it is written out as _x / ^x.
SUBSCRIPTS = {c: s for c, s in zip("0123456789+-=()aeoxhklmnpstijruv",
                                   "\u2080\u2081\u2082\u2083\u2084\u2085\u2086\u2087\u2088\u2089\u208a\u208b\u208c\u208d\u208e\u2090\u2091\u2092\u2093\u2095\u2096\u2097\u2098\u2099\u209a\u209b\u209c\u1d62\u2c7c\u1d63\u1d64\u1d65")}
SUPERSCRIPTS = {c: s for c, s in zip("0123456789+-=()abcdefghijklmnoprstuvwxyz",
                                     "\u2070\u00b9\u00b2\u00b3\u2074\u2075\u2076\u2077\u2078\u2079\u207a\u207b\u207c\u207d\u207e\u1d43\u1d47\u1d9c\u1d48\u1d49\u1da0\u1d4d\u02b0\u2071\u02b2\u1d4f\u02e1\u1d50\u207f\u1d52\u1d56\u02b3\u02e2\u1d57\u1d58\u1d5b\u02b7\u02e3\u02b8\u1dbb")}


# LaTeX commands that are set as upright words rather than symbols.
MATH_FUNCS = {"log", "exp", "ln", "max", "min", "arg", "argmax", "argmin", "sin",
              "cos", "tan", "det", "dim", "ker", "deg", "gcd", "sup", "inf"}
UNKNOWN_MATH = set()


def _math_word(name):
    r"""A \command: a symbol, an upright function name, or something we cannot
    render -- the last is collected so the build can report it."""
    if name in MATH_WORDS:
        return MATH_WORDS[name]
    if name not in MATH_FUNCS:
        UNKNOWN_MATH.add(name)
    return name


def _script(body, table, marker):
    """Sub/superscript `body` if every character has a unicode form -- a script
    is all-or-nothing, since a half-converted one ("e_id" -> "e\u1d62d") reads worse
    than the plain fallback."""
    body = re.sub(r"\s+", "", body)
    if body and all(c in table for c in body):
        return "".join(table[c] for c in body)
    return marker + body


def strip_math(text):
    """Inline LaTeX reads as noise on a slide. Render what unicode can express,
    and fall back to readable ASCII for the rest."""
    def one(m):
        body = m.group(1)
        body = (body.replace(r"\{", "\x00").replace(r"\}", "\x01")
                    .replace(r"\|", "\u2016"))          # literal braces and bars
        body = re.sub(r"\\(?:text|mathrm|mathit|mathbf|mathcal|mathbb|mathsf"
                      r"|boldsymbol|operatorname)\s*\{(.*?)\}", r"\1", body)
        body = re.sub(r"\\left|\\right|\\!|\\,|\\;|\\:|\\ ", " ", body)
        body = re.sub(r"\\([a-zA-Z]+)", lambda w: _math_word(w.group(1)), body)
        # Single-character scripts first: a braced script that cannot be rendered
        # falls back to "_id", and the single-char rule would then eat its "_i".
        body = re.sub(r"_(\w)", lambda g: _script(g.group(1), SUBSCRIPTS, "_"), body)
        body = re.sub(r"\^(\w)", lambda g: _script(g.group(1), SUPERSCRIPTS, "^"), body)
        body = re.sub(r"_\{(.*?)\}", lambda g: _script(g.group(1), SUBSCRIPTS, "_"), body)
        body = re.sub(r"\^\{(.*?)\}", lambda g: _script(g.group(1), SUPERSCRIPTS, "^"), body)
        body = body.replace("{", "").replace("}", "")
        body = body.replace("\x00", "{").replace("\x01", "}")
        return re.sub(r"\s+", " ", body).strip()
    return re.sub(r"\$(.+?)\$", one, text)



def plain(text):
    """clean_inline with emphasis markers removed, for single-run targets such as
    slide titles, which are styled as a whole and cannot carry mixed runs."""
    return re.sub(r"\*{1,2}|(?<![\w\\])_(?=\S)|(?<=\S)_(?![\w])", "", clean_inline(text))


def clean_inline(text):
    """Normalise a run of inline markdown to plain text."""
    text = re.sub(r"\[@([\w:\-]+)\]", lambda m: f"({CITES.get(m.group(1), m.group(1))})", text)
    text = strip_math(text)
    text = text.replace("''", '"').replace("`", "")
    return re.sub(r"\s+", " ", text).strip()


#  **bold**  |  *italic*  |  _italic_ -- the underscore form only between word
#  boundaries, so it never fires inside an identifier such as e_id or top_k.
EMPHASIS = re.compile(r"\*\*(.+?)\*\*"
                      r"|(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)"
                      r"|(?<![\w\\])_(?!\s)(.+?)(?<!\s)_(?![\w])")


def runs_of(text):
    """Split inline markdown into (text, bold, italic) runs."""
    text = clean_inline(text)
    out, pos = [], 0
    for m in EMPHASIS.finditer(text):
        if m.start() > pos:
            out.append((text[pos:m.start()], False, False))
        if m.group(1) is not None:
            out.append((m.group(1), True, False))
        else:
            out.append((m.group(2) if m.group(2) is not None else m.group(3), False, True))
        pos = m.end()
    if pos < len(text):
        out.append((text[pos:], False, False))
    return out or [(text, False, False)]


def parse_markdown(path):
    lines = open(path, encoding="utf-8").read().split("\n")
    blocks, i = [], 0
    while i < len(lines):
        raw = lines[i]
        line = raw.strip()

        if not line:
            i += 1
            continue

        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            blocks.append(dict(t="h", level=len(m.group(1)), text=plain(m.group(2))))
            i += 1
            continue

        if line.startswith("```"):
            lang = line[3:].strip()
            i += 1
            buf = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                buf.append(lines[i])
                i += 1
            i += 1
            blocks.append(dict(t="code", lang=lang, text="\n".join(buf)))
            continue

        if line.startswith(">"):
            buf = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                buf.append(re.sub(r"^>\s?", "", lines[i].strip()))
                i += 1
            blocks.append(dict(t="quote", text=" ".join(buf).strip()))
            continue

        m = re.match(r"^!\[(.*?)\]\((.+?)\)\s*$", line)
        if m:
            blocks.append(dict(t="img", alt=m.group(1).strip(), src=m.group(2).strip()))
            i += 1
            continue

        if line.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[\s:\-|]+\|$", lines[i + 1].strip()):
            def cells(s):
                return [c.strip() for c in s.strip().strip("|").split("|")]
            head = cells(line)
            i += 2
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append(cells(lines[i]))
                i += 1
            blocks.append(dict(t="table", head=head, rows=rows))
            continue

        if LIST_RE.match(line):
            items = []
            while i < len(lines):
                cur = lines[i].strip()
                m = LIST_RE.match(cur) if cur else None
                if m:
                    indent = len(lines[i]) - len(lines[i].lstrip())
                    items.append(dict(text=m.group(2), level=min(indent // 3, 2),
                                      ordered=m.group(1)[-1] == "."))
                elif cur and items and not re.match(r"^(#{1,6}\s|```|\||!\[)", cur):
                    items[-1]["text"] += " " + cur      # wrapped continuation line
                else:
                    break
                i += 1
            for it in items:
                it["text"] = clean_inline(it["text"])
            blocks.append(dict(t="bullets", items=items))
            continue

        buf = []
        while i < len(lines) and lines[i].strip() and not re.match(
                r"^(#{1,6}\s|```|\||!\[|>|[-*+]\s|\d+[.)]\s)", lines[i].strip()):
            buf.append(lines[i].strip())
            i += 1
        blocks.append(dict(t="para", text=" ".join(buf)))
    return blocks


def block_text_len(b):
    if b["t"] == "para":
        return len(b["text"])
    if b["t"] == "quote":
        return len(b["text"])
    if b["t"] == "bullets":
        return sum(len(x["text"]) for x in b["items"])
    return 999


# =============================================================================
# structure: sections -> units
# =============================================================================
def build_structure(blocks):
    doc_title, sections, cur = "Deck", [], dict(title=None, blocks=[])
    for b in blocks:
        if b["t"] == "h" and b["level"] == 1:
            doc_title = b["text"]
        elif b["t"] == "h" and b["level"] == 2:
            if cur["blocks"] or cur["title"]:
                sections.append(cur)
            cur = dict(title=b["text"], blocks=[])
        else:
            cur["blocks"].append(b)
    sections.append(cur)

    for s in sections:
        units, u = [], dict(head=None, level=2, parent=None, blocks=[])
        stack = []                      # (level, heading) of the open ancestors
        for b in s["blocks"]:
            if b["t"] == "h" and b["level"] >= 3:
                if u["blocks"] or u["head"]:
                    units.append(u)
                while stack and stack[-1][0] >= b["level"]:
                    stack.pop()
                u = dict(head=b["text"], level=b["level"],
                         parent=stack[-1][1] if stack else None, blocks=[])
                stack.append((b["level"], b["text"]))
            else:
                u["blocks"].append(b)
        units.append(u)
        s["units"] = [x for x in units if x["blocks"]]
    return doc_title, [s for s in sections if s["units"]]


def is_card_unit(u):
    if not u["head"]:
        return False
    if any(b["t"] in ("img", "table", "code") for b in u["blocks"]):
        return False
    return sum(block_text_len(b) for b in u["blocks"]) <= CARD_MAX_CHARS


def bold_led_cards(u):
    """A bold lead-in opens a card; the prose and lists that follow are its body,
    whether the lead-in is inline ("**Heuristics** - uses...") or a label on its
    own line. None if the unit is not shaped that way. Figures in the same unit
    are ignored here -- emit_unit gives each of them its own slide anyway."""
    cards, lede, kicker = [], "", ""
    for b in u["blocks"]:
        if b["t"] in ("img", "table", "code"):
            continue
        if b["t"] == "para" and b["text"].lstrip().startswith("**"):
            rs = runs_of(b["text"])
            head = rs[0][0].strip(" -–—:") if rs and rs[0][1] else ""
            # Keep the body as runs, not flat text -- emphasis inside a card body
            # ("**Tuple-based**, returning facts as...") has to survive.
            body = list(rs[1:] if head else rs)
            if body:
                t, bo, it = body[0]
                body[0] = (t.lstrip(" -–—:"), bo, it)
            cards.append(dict(head=head, body=body, bullets=[]))
        elif b["t"] == "quote":
            kicker = b["text"]           # "> ..." closes the slide under the cards
        elif not cards:
            # one short opening line is allowed, and heads the slide
            if b["t"] == "para" and not lede and block_text_len(b) < 330:
                lede = b["text"]
            else:
                return None
        elif b["t"] == "para":
            cards[-1]["body"] += [(" ", False, False)] + runs_of(b["text"])
        elif b["t"] == "bullets":
            cards[-1]["bullets"] += b["items"]
        else:
            return None
    for c in cards:
        c["body"] = [r for r in c["body"] if r[0]]
        c["text"] = "".join(t for t, _, _ in c["body"]).strip()
    if not 2 <= len(cards) <= 4:
        return None
    return dict(cards=cards, lede=lede, kicker=kicker)


def steps_block(u):
    """A flat numbered list of 4+ items -> a numbered steps slide."""
    for b in u["blocks"]:
        if (b["t"] == "bullets" and len(b["items"]) >= 4
                and all(i["ordered"] and i["level"] == 0 for i in b["items"])):
            return b
    return None


# =============================================================================
# drawing helpers
# =============================================================================
def textbox(slide, x, y, w, h, anchor=MSO_ANCHOR.TOP):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    return tf


def set_para(p, text_or_runs, size, color, font=BFONT, bold=False, italic=False,
             space_after=0, space_before=0, line=1.28, align=PP_ALIGN.LEFT, spacing=None):
    p.alignment = align
    p.space_after = Pt(space_after)
    p.space_before = Pt(space_before)
    p.line_spacing = line
    runs = text_or_runs if isinstance(text_or_runs, list) else [(text_or_runs, bold, italic)]
    for t, b, i in runs:
        if not t:
            continue
        r = p.add_run()
        r.text = t
        r.font.size = Pt(size)
        r.font.color.rgb = color
        r.font.name = font
        r.font.bold = b or bold
        r.font.italic = i or italic
        if spacing is not None:
            r.font._rPr.set("spc", str(int(spacing * 100)))
    return p


def rect(slide, x, y, w, h, fill=None, line=None, shape=MSO_SHAPE.ROUNDED_RECTANGLE,
         line_w=1.0, adj=0.06):
    s = slide.shapes.add_shape(shape, Inches(x), Inches(y), Inches(w), Inches(h))
    if shape == MSO_SHAPE.ROUNDED_RECTANGLE:
        try:
            s.adjustments[0] = adj
        except Exception:
            pass
    if fill is None:
        s.fill.background()
    else:
        s.fill.solid()
        s.fill.fore_color.rgb = fill
    if line is None:
        s.line.fill.background()
    else:
        s.line.color.rgb = line
        s.line.width = Pt(line_w)
    # shadow.inherit = False writes the empty <a:effectLst/> that kills the
    # shadow; appending a second one makes the file invalid and PowerPoint then
    # offers to "repair" it. Dropping p:style removes the theme's shadow too.
    s.shadow.inherit = False
    style = s._element.find(qn("p:style"))
    if style is not None:
        s._element.remove(style)
    return s


def bg(slide, color):
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = color


def _line_count(text, cpl):
    """Lines a greedy word-wrap would use. Counting characters alone under-counts
    a narrow column, where one long word ("Semantic-based") takes a line to
    itself and leaves the rest of it empty."""
    cpl = max(1, int(cpl))
    lines, cur = 1, 0
    for word in text.split():
        if cur == 0:
            used = len(word)
        elif cur + 1 + len(word) <= cpl:
            cur += 1 + len(word)
            continue
        else:
            lines += 1
            used = len(word)
        if used > cpl:                      # a word wider than the column
            lines += (used - 1) // cpl
            cur = used - ((used - 1) // cpl) * cpl
        else:
            cur = used
    return lines


def est_height(text, width_in, size_pt, line=1.28):
    """Conservative rendered height in inches for wrapped body text."""
    cpl = max(4, (width_in * 72) / (0.505 * size_pt))
    return _line_count(text, cpl) * size_pt * line / 72.0


def bullet_width(item):
    return CW - 0.34 - item["level"] * 0.34


def bullet_height(item):
    """A bullet is as tall as it wraps -- a long one must not sit on the next."""
    return max(0.30, est_height(item["text"], bullet_width(item), 15, line=1.30)) + 0.06


def est_height_serif(text, width_in, size_pt, line=1.18, widen=1.36):
    """As est_height, for headings set in HFONT. est_height is calibrated for
    Calibri; Georgia sets wider and wraps early on long words, so widen the
    per-character width only -- the line height itself is unchanged."""
    cpl = max(4, (width_in * 72) / (0.505 * size_pt * widen))
    return _line_count(text, cpl) * size_pt * line / 72.0


# =============================================================================
# slide builders
# =============================================================================
class Deck:
    def __init__(self, title):
        self.prs = Presentation()
        self.prs.slide_width = Inches(SW)
        self.prs.slide_height = Inches(SH)
        self.blank = self.prs.slide_layouts[6]
        self.title = title
        self.n = 0
        self.section_titles = set()

    def new(self, dark=False):
        s = self.prs.slides.add_slide(self.blank)
        bg(s, INK if dark else PAGE_BG)
        return s

    def chrome(self, slide, eyebrow, title):
        """Eyebrow + title + footer rule, used on every light content slide."""
        self.n += 1
        # A title already used in this section is a continuation, even if
        # another slide (a figure, say) came between the two.
        if title in self.section_titles:
            title += " (cont.)"
        else:
            self.section_titles.add(title)
        if eyebrow:
            tf = textbox(slide, ML, 0.62, CW, 0.26)
            set_para(tf.paragraphs[0], eyebrow.upper(), 10, SLATE, bold=True, spacing=1.4)
        lines = max(1, math.ceil(len(title) / 52.0))
        tf = textbox(slide, ML, 0.92, CW, 0.52 * lines + 0.10)
        set_para(tf.paragraphs[0], title, 30, SLATE_DK, font=HFONT, bold=True, line=1.06)

        ln = rect(slide, ML, 6.92, CW, 0.012, fill=RULE, shape=MSO_SHAPE.RECTANGLE)
        tf = textbox(slide, ML, 7.02, CW / 2, 0.24)
        set_para(tf.paragraphs[0], FOOTER, 9, MUTED)
        tf = textbox(slide, ML + CW / 2, 7.02, CW / 2, 0.24)
        set_para(tf.paragraphs[0], str(self.n), 9, MUTED, align=PP_ALIGN.RIGHT)
        return BODY_TOP + (lines - 1) * 0.46

    # -- motif -------------------------------------------------------------
    def node_motif(self, slide, x, y, scale=1.0):
        """Small abstract graph, echoing the figures. Used on dark slides."""
        pts = [(0, 0.62), (1.5, 0), (1.5, 1.3), (3.0, 0.72)]
        pts = [(x + a * scale, y + b * scale) for a, b in pts]
        for i, j in [(0, 1), (0, 2), (1, 3), (2, 3)]:
            c = slide.shapes.add_connector(
                1, Inches(pts[i][0] + 0.42 * scale), Inches(pts[i][1] + 0.16 * scale),
                Inches(pts[j][0]), Inches(pts[j][1] + 0.16 * scale))
            c.line.color.rgb = SLATE
            c.line.width = Pt(1.1)
        for k, (px, py) in enumerate(pts):
            col = OCHRE if k == 1 else SLATE
            rect(slide, px, py, 0.42 * scale, 0.32 * scale, fill=None, line=col, line_w=1.5, adj=0.18)

    # -- slide types -------------------------------------------------------
    def cover(self, src):
        """A ready-made title graphic, edge to edge. It already carries the deck
        title, so nothing is drawn over it."""
        s = self.new(dark=True)
        path = os.path.join(ROOT, src)
        pic = s.shapes.add_picture(path, 0, 0, width=Inches(SW))
        if pic.height < Inches(SH):        # cover the slide, never letterbox it
            pic._element.getparent().remove(pic._element)
            pic = s.shapes.add_picture(path, 0, 0, height=Inches(SH))
        pic.left = Emu(int((Inches(SW) - pic.width) / 2))
        pic.top = Emu(int((Inches(SH) - pic.height) / 2))

    def title_slide(self, subtitle, source):
        s = self.new(dark=True)
        tf = textbox(s, ML, 2.42, CW * 0.72, 0.3)
        set_para(tf.paragraphs[0], "RESEARCH REVIEW", 11, OCHRE, bold=True, spacing=1.8)
        tf = textbox(s, ML, 2.86, CW * 0.72, 1.3)
        set_para(tf.paragraphs[0], self.title, 54, WHITE, font=HFONT, bold=True, line=1.0)
        tf = textbox(s, ML, 4.24, CW * 0.60, 1.0)
        set_para(tf.paragraphs[0], subtitle, 17, ICE, line=1.35)
        if source:
            tf = textbox(s, ML, 6.30, CW * 0.72, 0.4)
            set_para(tf.paragraphs[0], source, 11, ICE)
        self.node_motif(s, 9.55, 2.95, scale=1.05)

    def divider(self, index, title):
        self.section_titles = set()
        s = self.new(dark=True)
        tf = textbox(s, ML, 2.55, CW, 1.0)
        set_para(tf.paragraphs[0], f"{index:02d}", 58, SLATE, font=HFONT, bold=True, line=1.0)
        tf = textbox(s, ML, 3.42, CW * 0.8, 1.2)
        set_para(tf.paragraphs[0], title, 40, WHITE, font=HFONT, bold=True, line=1.08)
        self.node_motif(s, 9.9, 5.1, scale=0.78)

    def content(self, eyebrow, title, blocks):
        """Body text + bullets, split across continuation slides if too tall."""
        pages, page, used = [], [], 0.0
        avail = BODY_BOT - BODY_TOP
        for b in blocks:
            if b["t"] == "para":
                h = est_height(b["text"], CW, 15) + 0.2
            elif b["t"] == "quote":
                h = est_height_serif(b["text"], CW - 0.30, 17) + 0.34
            elif b["t"] == "bullets":
                h = sum(bullet_height(it) for it in b["items"]) + 0.14
            else:
                h = 0.4
            if used + h > avail and page:
                pages.append(page)
                page, used = [], 0.0
            page.append(b)
            used += h
        if page:
            pages.append(page)

        for pi, pg in enumerate(pages):
            s = self.new()
            y = self.chrome(s, eyebrow, title + ("" if pi == 0 else " (cont.)"))
            for b in pg:
                if b["t"] == "para":
                    h = est_height(b["text"], CW, 15) + 0.14
                    tf = textbox(s, ML, y, CW, h)
                    set_para(tf.paragraphs[0], runs_of(b["text"]), 15, BODY, line=1.34)
                    y += h + 0.20
                elif b["t"] == "quote":
                    h = est_height_serif(b["text"], CW - 0.30, 17, line=1.34) + 0.10
                    rect(s, ML, y, 0.05, h, fill=OCHRE)
                    tf = textbox(s, ML + 0.30, y, CW - 0.30, h)
                    set_para(tf.paragraphs[0], runs_of(b["text"]), 17, SLATE_DK,
                             font=HFONT, italic=True, line=1.34)
                    y += h + 0.24
                elif b["t"] == "bullets":
                    for it in b["items"]:
                        x = ML + it["level"] * 0.34
                        rect(s, x + 0.04, y + 0.115, 0.10, 0.10,
                             fill=OCHRE if it["level"] == 0 else SLATE, adj=0.5)
                        tf = textbox(s, x + 0.34, y, bullet_width(it), bullet_height(it))
                        set_para(tf.paragraphs[0], runs_of(it["text"]), 15, BODY, line=1.30)
                        y += bullet_height(it)
                    y += 0.12

    def cards(self, eyebrow, title, units, lede=""):
        """Grid of up to 6 short sections, under an optional intro line."""
        s = self.new()
        top = self.chrome(s, eyebrow, title)
        if lede:
            lh = est_height(lede, CW, 14) + 0.10
            tf = textbox(s, ML, top - 0.06, CW, lh)
            set_para(tf.paragraphs[0], runs_of(lede), 14, MUTED, line=1.32)
            top += lh + 0.22
        n = len(units)
        cols = 3 if n > 4 else (n if n <= 3 else 2)
        rows = math.ceil(n / cols)
        gap = 0.32
        cw = (CW - gap * (cols - 1)) / cols
        avail = BODY_BOT - top
        ch = min(3.35, avail) if rows == 1 else (avail - gap * (rows - 1)) / rows
        for k, u in enumerate(units):
            r, c = divmod(k, cols)
            x = ML + c * (cw + gap)
            y = top + r * (ch + gap)
            accent = ACCENTS[k % len(ACCENTS)]
            rect(s, x, y, cw, ch, fill=CARD_BG, line=RULE, line_w=1.0)
            rect(s, x, y, 0.075, ch, fill=accent, shape=MSO_SHAPE.RECTANGLE)
            tf = textbox(s, x + 0.34, y + 0.28, cw - 0.62, 0.62)
            set_para(tf.paragraphs[0], u["head"], 15, SLATE_DK, font=HFONT, bold=True, line=1.12)
            body = " ".join(b["text"] for b in u["blocks"] if b["t"] == "para")
            bl = [b for b in u["blocks"] if b["t"] == "bullets"]
            yy = y + 0.28 + 0.62 + (0.10 if body else 0)
            if body:
                bh = ch - (yy - y) - 0.24
                bsize = 12.0
                while bsize > 10.0 and est_height(body, cw - 0.62, bsize, 1.30) > bh:
                    bsize -= 0.5
                tf = textbox(s, x + 0.34, yy, cw - 0.62, bh)
                set_para(tf.paragraphs[0], runs_of(body), bsize, MUTED, line=1.30)
            for b in bl:
                for it in b["items"]:
                    tf = textbox(s, x + 0.34, yy, cw - 0.62, 0.26)
                    set_para(tf.paragraphs[0], "— " + it, 12, MUTED)
                    yy += 0.28

    def pair(self, eyebrow, title, spec):
        """Side-by-side cards, one per bold-led paragraph, with an optional
        opening line above them and a closing kicker below."""
        cards, lede, kicker = spec["cards"], spec["lede"], spec["kicker"]
        s = self.new()
        top = self.chrome(s, eyebrow, title)
        bot = BODY_BOT
        if lede:
            lh = est_height(lede, CW, 14) + 0.10
            tf = textbox(s, ML, top - 0.06, CW, lh)
            set_para(tf.paragraphs[0], runs_of(lede), 14, MUTED, line=1.32)
            top += lh + 0.24
        if kicker:
            kh = est_height_serif(kicker, CW - 0.30, 16, line=1.34) + 0.10
            bot -= kh + 0.34
            rect(s, ML, bot + 0.34, 0.05, kh, fill=OCHRE)
            tf = textbox(s, ML + 0.30, bot + 0.34, CW - 0.30, kh)
            set_para(tf.paragraphs[0], runs_of(kicker), 16, SLATE_DK,
                     font=HFONT, italic=True, line=1.34)
        gap, n = 0.42, len(cards)
        cw = (CW - gap * (n - 1)) / n
        h = bot - top
        hsize = 20 if n < 4 else 18

        # One head band for the whole row, sized to the tallest heading, so every
        # card's body starts on the same line.
        hh = max([0.50] + [est_height_serif(c["head"], cw - 0.80, hsize) + 0.08
                           for c in cards])

        def head_height(c):
            return hh

        def fill_height(c, size):
            """How tall a card's contents run at this body size."""
            y = 0.42 + head_height(c) + 0.10
            if c["text"]:
                y += est_height(c["text"], cw - 0.80, size) + 0.26
            for it in c["bullets"]:
                y += est_height(it["text"], cw - 1.10, size - 1) + 0.18
            return y + 0.34

        size = 14 if n < 4 else 13
        while size > 10 and max(fill_height(c, size) for c in cards) > h:
            size -= 1

        for k, c in enumerate(cards):
            x = ML + k * (cw + gap)
            accent = ACCENTS[k % len(ACCENTS)]
            rect(s, x, top, cw, h, fill=CARD_BG, line=RULE, line_w=1.0)
            rect(s, x, top, cw, 0.075, fill=accent, shape=MSO_SHAPE.RECTANGLE)
            hh = head_height(c)
            tf = textbox(s, x + 0.40, top + 0.42, cw - 0.80, hh)
            set_para(tf.paragraphs[0], c["head"], hsize, accent,
                     font=HFONT, bold=True, line=1.12)
            y = top + 0.42 + hh + 0.10
            if c["text"]:
                bh = est_height(c["text"], cw - 0.80, size) + 0.10
                tf = textbox(s, x + 0.40, y, cw - 0.80, bh)
                set_para(tf.paragraphs[0], c["body"], size, BODY, line=1.36)
                y += bh + 0.16
            for it in c["bullets"]:
                ih = est_height(it["text"], cw - 1.10, size - 1) + 0.06
                rect(s, x + 0.44, y + 0.11, 0.09, 0.09, fill=accent, adj=0.5)
                tf = textbox(s, x + 0.72, y, cw - 1.12, ih)
                set_para(tf.paragraphs[0], runs_of(it["text"]), size - 1, BODY, line=1.30)
                y += ih + 0.12

    def steps(self, eyebrow, title, items, lede=""):
        """A numbered sequence: one chip-and-text row per step."""
        s = self.new()
        top = self.chrome(s, eyebrow, title)
        if lede:
            h = est_height(lede, CW, 14) + 0.10
            tf = textbox(s, ML, top - 0.06, CW, h)
            set_para(tf.paragraphs[0], runs_of(lede), 14, MUTED, line=1.32)
            top += h + 0.22
        n = len(items)
        size = 15 if n <= 5 else 14
        tw = CW - 0.76
        # Rows are as tall as the step that sits in them, so a step that wraps
        # onto two lines does not leave a broken connector behind it.
        def measure(size):
            rows = [max(0.52, est_height(it["text"], tw, size, line=1.30)) for it in items]
            return rows, (BODY_BOT - top - sum(rows)) / max(1, n - 1)

        rows, pad = measure(size)
        while size > 11 and pad < 0.14:
            size -= 1
            rows, pad = measure(size)
        pad = min(0.34, max(0.08, pad))
        y = top
        for k, it in enumerate(items):
            rect(s, ML, y, 0.44, 0.44, fill=ACCENTS[k % len(ACCENTS)], adj=0.5)
            tf = textbox(s, ML, y + 0.055, 0.44, 0.34)
            set_para(tf.paragraphs[0], str(k + 1), 15, WHITE, font=HFONT,
                     bold=True, align=PP_ALIGN.CENTER)
            if k < n - 1:
                rect(s, ML + 0.205, y + 0.46, 0.03, rows[k] + pad - 0.48, fill=RULE)
            tf = textbox(s, ML + 0.76, y + 0.02, tw, rows[k])
            set_para(tf.paragraphs[0], runs_of(it["text"]), size, BODY, line=1.30)
            y += rows[k] + pad

    def figure(self, eyebrow, title, src, caption, lede=""):
        s = self.new()
        top = self.chrome(s, eyebrow, title)
        if lede:
            h = est_height(lede, CW, 14) + 0.10
            tf = textbox(s, ML, top - 0.10, CW, h)
            set_para(tf.paragraphs[0], runs_of(lede), 14, MUTED, line=1.32)
            top += h + 0.12
        path = os.path.join(ROOT, src)
        if not os.path.exists(path):
            tf = textbox(s, ML, BODY_TOP, CW, 0.4)
            set_para(tf.paragraphs[0], f"[missing image: {src}]", 14, CROSS, italic=True)
            return
        box_h = (BODY_BOT - top) - (0.42 if caption else 0)
        pic = s.shapes.add_picture(path, Inches(ML), Inches(top), width=Inches(CW))
        if pic.height > Inches(box_h):
            pic._element.getparent().remove(pic._element)
            pic = s.shapes.add_picture(path, Inches(ML), Inches(top), height=Inches(box_h))
        pic.left = Emu(int(Inches(ML) + (Inches(CW) - pic.width) / 2))
        pic.top = Emu(int(Inches(top) + (Inches(box_h) - pic.height) / 2))
        if caption:
            tf = textbox(s, ML, BODY_BOT - 0.34, CW, 0.32)
            set_para(tf.paragraphs[0], caption, 11.5, MUTED, italic=True, align=PP_ALIGN.CENTER)

    def table(self, eyebrow, title, head, rows):
        nc = len(head)
        vmargin, hdr, pad = 0.03, 0.46, 0.28

        def cell_text(row, c):
            return clean_inline(row[c]) if c < len(row) else ""

        # Columns share the width in proportion to the text they carry, so a
        # column of one-word labels cannot crowd out a column of prose.
        weights = []
        for c in range(nc):
            lens = [len(cell_text(r, c)) for r in rows] or [0]
            weights.append(max(8.0, len(clean_inline(head[c])), sum(lens) / len(lens)))
        widths = [CW * w / sum(weights) for w in weights]
        widths = [max(0.95, w) for w in widths]
        widths = [w * CW / sum(widths) for w in widths]

        def row_height(row, size):
            """Tallest cell in the row once its text wraps to the column width."""
            n = max(_line_count(cell_text(row, c),
                                max(4, ((widths[c] - pad) * 72) / (0.505 * size)))
                    for c in range(nc)) if nc else 1
            return n * size * 1.30 / 72 + 2 * vmargin + 0.10

        avail = BODY_BOT - BODY_TOP - hdr
        bsize = 13.0
        while bsize > 9.5 and sum(row_height(r, bsize) for r in rows) > avail:
            bsize -= 0.5

        # Pack by measured height, so a table of wrapping prose splits onto a
        # second slide instead of running off the bottom of the first.
        chunks, chunk, used = [], [], 0.0
        for r in rows:
            h = row_height(r, bsize)
            if chunk and (used + h > avail or len(chunk) >= MAX_TABLE_ROWS):
                chunks.append(chunk)
                chunk, used = [], 0.0
            chunk.append(r)
            used += h
        chunks.append(chunk)

        for ci, chunk in enumerate(chunks):
            s = self.new()
            top = self.chrome(s, eyebrow, title + ("" if ci == 0 else " (cont.)"))
            nr = len(chunk) + 1
            heights = [row_height(r, bsize) for r in chunk]
            th = hdr + sum(heights)
            gf = s.shapes.add_table(nr, nc, Inches(ML), Inches(top), Inches(CW), Inches(th))
            tbl = gf.table
            tbl.first_row = True
            for c in range(nc):
                tbl.columns[c].width = Inches(widths[c])
            tbl.rows[0].height = Inches(hdr)
            for r in range(1, nr):
                tbl.rows[r].height = Inches(heights[r - 1])

            for c, htxt in enumerate(head):
                cell = tbl.cell(0, c)
                cell.fill.solid()
                cell.fill.fore_color.rgb = SLATE_DK
                cell.margin_left = cell.margin_right = Inches(0.14)
                cell.vertical_anchor = MSO_ANCHOR.MIDDLE
                set_para(cell.text_frame.paragraphs[0], runs_of(htxt), bsize - 0.5, WHITE,
                         bold=True, align=PP_ALIGN.LEFT if c == 0 else PP_ALIGN.CENTER)

            for r, row in enumerate(chunk, start=1):
                for c in range(nc):
                    raw = row[c] if c < len(row) else ""
                    cell = tbl.cell(r, c)
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = WHITE if r % 2 else RGBColor(0xF3, 0xF6, 0xF8)
                    cell.margin_left = cell.margin_right = Inches(0.14)
                    cell.margin_top = cell.margin_bottom = Inches(vmargin)
                    cell.vertical_anchor = MSO_ANCHOR.MIDDLE
                    txt = clean_inline(raw)
                    # runs, so **bold** inside a cell renders instead of printing
                    content, col, size, bold = runs_of(raw), BODY, bsize, False
                    if txt in ("✅", "✓", "yes"):
                        content, col, size, bold = "✓", TICK, bsize + 3, True
                    elif txt in ("❌", "✗", "no"):
                        content, col, size, bold = "✗", CROSS, bsize + 3, True
                    set_para(cell.text_frame.paragraphs[0], content, size, col, bold=bold,
                             align=PP_ALIGN.LEFT if c == 0 else PP_ALIGN.CENTER)

    def closing(self, text):
        s = self.new(dark=True)
        tf = textbox(s, ML, 1.68, CW * 0.7, 0.3)
        set_para(tf.paragraphs[0], "WHERE THIS LEAVES US", 11, OCHRE, bold=True, spacing=1.8)
        tf = textbox(s, ML, 2.30, CW * 0.74, 3.6)
        set_para(tf.paragraphs[0], runs_of(text), 22, WHITE, font=HFONT, line=1.42)
        self.node_motif(s, 9.9, 5.55, scale=0.78)

    def bibliography(self, entries, eyebrow):
        """Numbered reference list. Two columns, each read top to bottom."""
        per_slide = 10
        chunks = [entries[i:i + per_slide] for i in range(0, len(entries), per_slide)]
        for ci, chunk in enumerate(chunks):
            s = self.new()
            top = self.chrome(s, eyebrow, "References")
            gap = 0.50
            cw = (CW - gap) / 2
            rows = int(math.ceil(len(chunk) / 2.0))
            eh = (BODY_BOT - top) / max(1, rows)
            tw = cw - 0.46
            for k, rec in enumerate(chunk):
                col, row = divmod(k, rows)      # column-major, so numbering reads down
                x, y = ML + col * (cw + gap), top + row * eh
                tf = textbox(s, x, y, 0.40, 0.34)
                set_para(tf.paragraphs[0], f"{ci * per_slide + k + 1:02d}", 12,
                         ACCENTS[k % len(ACCENTS)], font=HFONT, bold=True)
                # Title and meta share one frame so the meta always follows the
                # last line of the title, however the title happens to wrap.
                size = 12.0
                while size > 9.5 and est_height_serif(rec["title"], tw, size) > eh - 0.30:
                    size -= 0.5
                tf = textbox(s, x + 0.46, y - 0.02, tw, eh - 0.10)
                set_para(tf.paragraphs[0], rec["title"], size, SLATE_DK, font=HFONT,
                         bold=True, line=1.18)
                set_para(tf.add_paragraph(), reference_meta(rec), 10, MUTED,
                         space_before=5)

    def save(self):
        self.prs.save(OUT)


# =============================================================================
# planning
# =============================================================================
def caption_for(b):
    alt = b.get("alt", "")
    if alt and not re.match(r"^\S+\.(png|jpe?g|svg|gif)$", alt, re.I):
        return alt
    return CAPTIONS.get(os.path.basename(b["src"]), "")


def drop_final_stop(text):
    """Remove a full stop closing a sentence, but keep one that belongs to an
    abbreviation, so 'Han et al.' does not become 'Han et al'."""
    if not text.endswith("."):
        return text
    last = text[:-1].split()[-1] if text[:-1].split() else ""
    return text if len(last.rstrip(".")) <= 3 else text[:-1]


def image_title_and_caption(b):
    """A caption short enough to be a title becomes one; never show both."""
    cap = caption_for(b)
    if not cap:
        print(f"  ! no caption for {b['src']} -- give it alt text in the markdown, "
              f"or add it to CAPTIONS in scripts/build_deck.py", file=sys.stderr)
        return "Figure", ""
    if len(cap) <= 82:
        return drop_final_stop(cap), ""
    head = re.split(r"[:;,]", cap)[0].strip()
    return (head if 8 <= len(head) <= 82 else "Figure"), cap


def eyebrow_of(sec, u):
    """Section name, plus the heading this unit sits under -- so a subsection
    reads as one of its parent's options rather than a peer of it."""
    bits = [sec["title"] or ""] + ([u["parent"]] if u.get("parent") else [])
    return "  \u00b7  ".join(b for b in bits if b)


def emit_unit(deck, eyebrow, u):
    """Turn one H3 unit (or a section intro) into slides."""
    head = u["head"] or eyebrow
    text_blocks = [b for b in u["blocks"] if b["t"] in ("para", "bullets", "quote")]
    visuals = [b for b in u["blocks"] if b["t"] in ("img", "table", "code")]

    cards = bold_led_cards(u) if u["head"] else None
    if cards:
        deck.pair(eyebrow, u["head"], cards)
        text_blocks = []

    steps = steps_block(u) if u["head"] and not cards else None
    if steps:
        i = u["blocks"].index(steps)
        before = [b for b in u["blocks"][:i] if b["t"] in ("para", "bullets", "quote")]
        after = [b for b in u["blocks"][i + 1:] if b["t"] in ("para", "bullets", "quote")]
        # a short run-in line ("...takes the following steps:") heads the steps
        # slide rather than trailing the slide before it.
        lede = ""
        if before and before[-1]["t"] == "para" and block_text_len(before[-1]) < 120:
            lede = before.pop()["text"]
        if before:
            deck.content(eyebrow, head, before)
        deck.steps(eyebrow, head, steps["items"], lede)
        if after:
            deck.content(eyebrow, head + " (cont.)", after)
        text_blocks = []

    # A one-line intro sitting in front of a figure reads better as a lede on
    # that figure than as a near-empty slide of its own.
    lede = ""
    if (text_blocks and visuals
            and all(b["t"] == "para" for b in text_blocks)
            and sum(block_text_len(b) for b in text_blocks) < 150):
        lede = " ".join(b["text"] for b in text_blocks)
        text_blocks = []

    if text_blocks:
        deck.content(eyebrow, head, text_blocks)

    for b in u["blocks"]:
        if b["t"] == "img":
            title, cap = image_title_and_caption(b)
            deck.figure(eyebrow, title, b["src"], cap, lede=lede)
            lede = ""
        elif b["t"] == "table":
            deck.table(eyebrow, head, b["head"], b["rows"])
        elif b["t"] == "code":
            src = next((v for k, v in MERMAID_MAP.items() if k in b["text"]), None)
            if src:
                deck.figure(eyebrow, "The GraphRAG pipeline", src,
                            "How a query moves through the four stages", lede=lede)
                lede = ""
            else:
                print(f"  ! unmapped {b['lang'] or 'code'} block skipped "
                      f"(add it to MERMAID_MAP in scripts/build_deck.py)", file=sys.stderr)


def main():
    blocks = parse_markdown(SRC)
    doc_title, sections = build_structure(blocks)

    source = ""
    for b in blocks:
        if b["t"] == "para":
            m = re.search(r"\(([^)]*\d{4})\)", clean_inline(b["text"]))
            if m:
                source = "Source: " + m.group(1)
            break

    # An image placed above the H1 is a ready-made title graphic: it becomes the
    # opening slide in place of the generated one, and gets no figure slide.
    cover = blocks[0] if blocks and blocks[0]["t"] == "img" else None
    if cover and not os.path.exists(os.path.join(ROOT, cover["src"])):
        print(f"  ! missing cover image {cover['src']}", file=sys.stderr)
        cover = None
    if cover:
        for sec in sections:
            for u in sec["units"]:
                if cover in u["blocks"]:
                    u["blocks"].remove(cover)
        for sec in sections:
            sec["units"] = [u for u in sec["units"] if u["blocks"]]
        sections = [s for s in sections if s["units"]]

    deck = Deck(doc_title)
    if cover:
        deck.cover(cover["src"])
    else:
        deck.title_slide(DECK_SUBTITLE, source)

    last_para = None
    if CLOSING_FROM_LAST_PARA:
        for sec in reversed(sections):
            for u in reversed(sec["units"]):
                paras = [b for b in u["blocks"] if b["t"] == "para"]
                if paras and len(u["blocks"]) > 1:
                    last_para = paras[-1]["text"]
                    u["blocks"].remove(paras[-1])   # shown on the closing slide instead
                    break
            if last_para:
                break

    idx = 0
    for si, sec in enumerate(sections):
        eyebrow = sec["title"] or doc_title
        if sec["title"]:
            idx += 1
            deck.divider(idx, sec["title"])

        i, units = 0, sec["units"]
        while i < len(units):
            u = units[i]

            # A heading whose body is only an intro line and which is followed by
            # its own subsections is the title for them, not a card beside them.
            title, lede = None, ""
            sibs = [x for x in units[i + 1:] if x["level"] == u["level"] + 1]
            if (u["head"] and len(sibs) >= 2 and all(is_card_unit(x) for x in sibs[:2])
                    and all(b["t"] == "para" for b in u["blocks"])
                    and sum(block_text_len(b) for b in u["blocks"]) < 330):
                title = u["head"]
                lede = " ".join(b["text"] for b in u["blocks"])
                i += 1
                u = units[i]

            if is_card_unit(u):
                lvl, group = u["level"], []
                while (i < len(units) and is_card_unit(units[i])
                       and units[i]["level"] == lvl and len(group) < 6):
                    group.append(units[i])
                    i += 1
                if len(group) == 1 and not title:
                    emit_unit(deck, eyebrow_of(sec, group[0]), group[0])
                else:
                    deck.cards(eyebrow, title or sec["title"] or "Overview", group, lede)
                continue

            emit_unit(deck, eyebrow_of(sec, u), u)
            i += 1

    if last_para:
        deck.closing(last_para)

    refs = bibliography_entries()
    if refs:
        deck.bibliography(refs, doc_title)

    if UNKNOWN_MATH:
        print("  ! no symbol for " + ", ".join("\\" + c for c in sorted(UNKNOWN_MATH))
              + " -- add it to MATH_WORDS in scripts/build_deck.py", file=sys.stderr)

    deck.save()
    print(f"wrote {OUT}  ({len(deck.prs.slides.__iter__.__self__._sldIdLst)} slides)")


if __name__ == "__main__":
    main()
